#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 12 15:29:58 2018

@author: soenke
"""

class deconv_net:
    
    def __init__(self):
        # set params
        pass
    
    def train(self, n_epochs):
        pass
    
    def run_on_image(self, im):
        # im: np-array
        pass
    
    def test(self):
        pass

    
    